// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectory() {
  return window['go']['main']['app']['OpenDirectory']();
}

export function Organize(arg1, arg2) {
  return window['go']['main']['app']['Organize'](arg1, arg2);
}
